[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/tokens/address/*"
  to = "/.netlify/functions/getTokenByAddress"
  status = 200

[[redirects]]
  from = "/api/tokens"
  to = "/.netlify/functions/getTokens"
  status = 200

[[redirects]]
  from = "/api/token_purchases"
  to = "/.netlify/functions/getTokenPurchases"
  status = 200

[[redirects]]
  from = "/api/market-data/*"
  to = "/.netlify/functions/getMarketData"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 