[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/tokens/address/:address"
  to = "/.netlify/functions/getTokenByAddress/:address"
  status = 200
  force = true

[[redirects]]
  from = "/api/tokens"
  to = "/.netlify/functions/getTokens"
  status = 200

[[redirects]]
  from = "/api/token_purchases"
  to = "/.netlify/functions/getTokenPurchases"
  status = 200

[[redirects]]
  from = "/api/tokens/add"
  to = "/.netlify/functions/addToken"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200

[[redirects]]
  from = "/twitter-auth"
  to = "/.netlify/functions/twitter-auth"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 